import React, { useState, useEffect } from 'react';
import * as LucideIcons from 'lucide-react';
import { useConfig } from '@/hooks/useConfig';

export const EMOJI_TO_LUCIDE: Record<string, string> = {
  '🗄️': 'Server',
  '💽': 'HardDrive',
  '⚡': 'Cpu',
  '🐘': 'Database',
  '👨‍💻': 'Terminal',
  '🐍': 'Code',
  '🐙': 'GitBranch',
  '📍': 'GitCommit',
  '🔀': 'GitPullRequest',
  '🐳': 'Container',
  '🤖': 'Bot',
  '🖥️': 'Monitor',
  '💻': 'Laptop',
  '📱': 'Smartphone',
  '📲': 'Tablet',
  '☁️': 'Cloud',
  '🌩️': 'CloudUpload',
  '📡': 'CloudDownload',
  '📶': 'Wifi',
  '🛰️': 'Router',
  '📻': 'Radio',
  '🛸': 'Satellite',
  '🔌': 'Plug',
  '🔋': 'Battery',
  '💾': 'Save',
  '🖨️': 'Printer',
  '⌨️': 'Keyboard',
  '🖱️': 'Mouse',
  '⌚': 'Watch',
  '📺': 'Tv',
  '🎮': 'Gamepad',
  '🕹️': 'Gamepad2',
  '💿': 'Disc',
  '🔬': 'Binary',
  '🔍': 'Scan',
  '🛡️': 'Shield',
  '🦀': 'ShieldAlert',
  '✅': 'ShieldCheck',
  '🔒': 'Lock',
  '🔓': 'Unlock',
  '🔑': 'Key',
  '🐛': 'Bug',
  '🧪': 'FlaskConical',
  '🔥': 'Flame',
  '⚽': 'Activity',
  '🌍': 'Globe',
  '🕸️': 'Network',
  '📁': 'Folder',
  '📂': 'FolderOpen',
  '➕': 'FolderPlus',
  '📄': 'File',
  '📝': 'FileText',
  '📜': 'FileCode',
  '🗂️': 'Files',
  '🗃️': 'Archive',
  '📋': 'Clipboard',
  '📓': 'Book',
  '📖': 'BookOpen',
  '🔖': 'Bookmark',
  '🏷️': 'Tag',
  '📎': 'Paperclip',
  '🖊️': 'PenTool',
  '✏️': 'Pencil',
  '🎨': 'Palette',
  '📷': 'Camera',
  '📹': 'Video',
  '🎬': 'Film',
  '🍿': 'Clapperboard',
  '🎤': 'Mic',
  '🎙️': 'MicOff',
  '🎧': 'Headphones',
  '🎵': 'Music',
  '🔊': 'Volume2',
  '🔇': 'VolumeX',
  '🎚️': 'Sliders',
  '🖼️': 'Image',
  '📰': 'Newspaper',
  '📊': 'BarChart',
  '📈': 'BarChart2',
  '📉': 'PieChart',
  '✔️': 'Check',
  '❌': 'X',
  '✖️': 'XCircle',
  '➖': 'Minus',
  '❓': 'HelpCircle',
  '❕': 'AlertCircle',
  '⚠️': 'AlertTriangle',
  'ℹ️': 'Info',
  '⚙️': 'Settings',
  '🔧': 'Wrench',
  '🔨': 'Hammer',
  '🪜': 'Menu',
  '💬': 'MoreHorizontal',
  '💭': 'MoreVertical',
  '🧩': 'Grid',
  '🪟': 'Layout',
  '👁️': 'Eye',
  '🙈': 'EyeOff',
  '☀️': 'Sun',
  '🌙': 'Moon',
  '✨': 'Sparkles',
  '⭐': 'Star',
  '❤️': 'Heart',
  '😀': 'Smile',
  '🙁': 'Frown',
  '👍': 'ThumbsUp',
  '👎': 'ThumbsDown',
  '👤': 'User',
  '👥': 'Users',
  '🚪': 'LogIn',
  '⬅️': 'ArrowLeft',
  '➡️': 'ArrowRight',
  '⬆️': 'ArrowUp',
  '⬇️': 'ArrowDown',
  '◀️': 'ChevronLeft',
  '▶️': 'ChevronRight',
  '🔼': 'ChevronUp',
  '🔽': 'ChevronDown',
  '🔄': 'RefreshCw',
  '🌀': 'RotateCw',
  '↩️': 'RotateCcw',
  '🔗': 'ExternalLink',
  '⛓️': 'Unlink',
  '📢': 'Share2',
  '🚀': 'Send',
  '✉️': 'Mail',
  '📥': 'Inbox',
  '🔔': 'Bell',
  '🔕': 'BellOff',
  '🏠': 'Home',
  '🏢': 'Building',
  '🏭': 'Building2',
  '🏗️': 'Construction',
  '🛋️': 'Bed',
  '🛁': 'Bath',
  '🚿': 'ShowerHead',
  '💧': 'Droplet',
  '🌊': 'Waves',
  '❄️': 'Snowflake',
  '💨': 'Wind',
  '🧭': 'Compass',
  '🗺️': 'Map',
  '⛵': 'Navigation',
  '⚓': 'Anchor',
  '🚗': 'Car',
  '🚚': 'Truck',
  '🚌': 'Bus',
  '🚲': 'Bike',
  '✈️': 'Plane',
  '🚢': 'Ship',
  '💼': 'Briefcase',
  '🧺': 'ShoppingBag',
  '🛒': 'ShoppingCart',
  '💳': 'CreditCard',
  '💵': 'DollarSign',
  '💶': 'Euro',
  '🎁': 'Gift',
  '🏆': 'Trophy',
  '🥇': 'Award',
  '🎖️': 'Medal',
  '👑': 'Crown',
  '🎯': 'Target',
  '🕒': 'Clock',
  '📅': 'Calendar',
  '⏱️': 'Timer',
  '⏳': 'Hourglass',
  '⚖️': 'Scale',
  '✂️': 'Scissors',
  '📦': 'Box',
  '📚': 'Layers',
  '☕': 'Coffee',
  '🍽️': 'Utensils',
  '🍕': 'Pizza',
  '🌤️': 'SunDim',
  '⛅': 'CloudSun',
  '🌧️': 'CloudRain',
  '🌲': 'Trees',
  '🌱': 'Sprout',
  '🍎': 'Apple',
  '🐱': 'Cat',
  '🐶': 'Dog',
  '🐰': 'Rabbit',
  '🐿️': 'Squirrel',
  '🐦': 'Bird',
  '🐟': 'Fish',
  '🐢': 'Turtle',
  '🐌': 'Snail',
  '💡': 'Lightbulb',
  '👓': 'Glasses',
  '🎫': 'Ticket',
  '🎉': 'PartyPopper',
  '🗑️': 'Trash',
  '📤': 'Upload',
  '📟': 'TerminalSquare',
  '📑': 'FileCheck',
  '🌐': 'Globe2',
  '📌': 'Pin',
  '💔': 'HeartOff',
  '🔐': 'LockKeyhole',
  '🔎': 'FileSearch',
  '🌁': 'AArrowDown',
  '🌂': 'AArrowDownIcon',
  '🌃': 'AArrowUp',
  '🌄': 'AArrowUpIcon',
  '🌅': 'ALargeSmall',
  '🌆': 'ALargeSmallIcon',
  '🌇': 'Accessibility',
  '🌈': 'AccessibilityIcon',
  '🌉': 'ActivityIcon',
  '🌋': 'ActivitySquare',
  '🌌': 'ActivitySquareIcon',
  '🌎': 'AirVent',
  '🌏': 'AirVentIcon',
  '🌑': 'Airplay',
  '🌒': 'AirplayIcon',
  '🌓': 'AlarmCheck',
  '🌔': 'AlarmCheckIcon',
  '🌕': 'AlarmClock',
  '🌖': 'AlarmClockCheck',
  '🌗': 'AlarmClockCheckIcon',
  '🌘': 'AlarmClockIcon',
  '🌚': 'AlarmClockMinus',
  '🌛': 'AlarmClockMinusIcon',
  '🌜': 'AlarmClockOff',
  '🌝': 'AlarmClockOffIcon',
  '🌞': 'AlarmClockPlus',
  '🌟': 'AlarmClockPlusIcon',
  '🌠': 'AlarmMinus',
  '🌡': 'AlarmMinusIcon',
  '🌢': 'AlarmPlus',
  '🌣': 'AlarmPlusIcon',
  '🌤': 'AlarmSmoke',
  '🌥': 'AlarmSmokeIcon',
  '🌦': 'Album',
  '🌧': 'AlbumIcon',
  '🌨': 'AlertCircleIcon',
  '🌩': 'AlertOctagon',
  '🌪': 'AlertOctagonIcon',
  '🌫': 'AlertTriangleIcon',
  '🌬': 'AlignCenter',
  '🌭': 'AlignCenterHorizontal',
  '🌮': 'AlignCenterHorizontalIcon',
  '🌯': 'AlignCenterIcon',
  '🌰': 'AlignCenterVertical',
  '🌳': 'AlignCenterVerticalIcon',
  '🌴': 'AlignEndHorizontal',
  '🌵': 'AlignEndHorizontalIcon',
  '🌶': 'AlignEndVertical',
  '🌷': 'AlignEndVerticalIcon',
  '🌸': 'AlignHorizontalDistributeCenter',
  '🌹': 'AlignHorizontalDistributeCenterIcon',
  '🌺': 'AlignHorizontalDistributeEnd',
  '🌻': 'AlignHorizontalDistributeEndIcon',
  '🌼': 'AlignHorizontalDistributeStart',
  '🌽': 'AlignHorizontalDistributeStartIcon',
  '🌾': 'AlignHorizontalJustifyCenter',
  '🌿': 'AlignHorizontalJustifyCenterIcon',
  '🍀': 'AlignHorizontalJustifyEnd',
  '🍁': 'AlignHorizontalJustifyEndIcon',
  '🍂': 'AlignHorizontalJustifyStart',
  '🍃': 'AlignHorizontalJustifyStartIcon',
  '🍄': 'AlignHorizontalSpaceAround',
  '🍅': 'AlignHorizontalSpaceAroundIcon',
  '🍆': 'AlignHorizontalSpaceBetween',
  '🍇': 'AlignHorizontalSpaceBetweenIcon',
  '🍈': 'AlignJustify',
  '🍉': 'AlignJustifyIcon',
  '🍊': 'AlignLeft',
  '🍋': 'AlignLeftIcon',
  '🍌': 'AlignRight',
  '🍍': 'AlignRightIcon',
  '🍏': 'AlignStartHorizontal',
  '🍐': 'AlignStartHorizontalIcon',
  '🍑': 'AlignStartVertical',
  '🍒': 'AlignStartVerticalIcon',
  '🍓': 'AlignVerticalDistributeCenter',
  '🍔': 'AlignVerticalDistributeCenterIcon',
  '🍖': 'AlignVerticalDistributeEnd',
  '🍗': 'AlignVerticalDistributeEndIcon',
  '🍘': 'AlignVerticalDistributeStart',
  '🍙': 'AlignVerticalDistributeStartIcon',
  '🍚': 'AlignVerticalJustifyCenter',
  '🍛': 'AlignVerticalJustifyCenterIcon',
  '🍜': 'AlignVerticalJustifyEnd',
  '🍝': 'AlignVerticalJustifyEndIcon',
  '🍞': 'AlignVerticalJustifyStart',
  '🍟': 'AlignVerticalJustifyStartIcon',
  '🍠': 'AlignVerticalSpaceAround',
  '🍡': 'AlignVerticalSpaceAroundIcon',
  '🍢': 'AlignVerticalSpaceBetween',
  '🍣': 'AlignVerticalSpaceBetweenIcon',
  '🍤': 'Ambulance',
  '🍥': 'AmbulanceIcon',
  '🍦': 'Ampersand',
  '🍧': 'AmpersandIcon',
  '🍨': 'Ampersands',
  '🍩': 'AmpersandsIcon',
  '🍪': 'Amphora',
  '🍫': 'AmphoraIcon',
  '🍬': 'AnchorIcon',
  '🍭': 'Angry',
  '🍮': 'AngryIcon',
  '🍯': 'Annoyed',
  '🍰': 'AnnoyedIcon',
  '🍱': 'Antenna',
  '🍲': 'AntennaIcon',
  '🍳': 'Anvil',
  '🍴': 'AnvilIcon',
  '🍵': 'Aperture',
  '🍶': 'ApertureIcon',
  '🍷': 'AppWindow',
  '🍸': 'AppWindowIcon',
  '🍹': 'AppWindowMac',
  '🍺': 'AppWindowMacIcon',
  '🍻': 'AppleIcon',
  '🍼': 'ArchiveIcon',
  '🍽': 'ArchiveRestore',
  '🍾': 'ArchiveRestoreIcon',
  '🎀': 'ArchiveX',
  '🎂': 'ArchiveXIcon',
  '🎃': 'AreaChart',
  '🎄': 'AreaChartIcon',
  '🎅': 'Armchair',
  '🎆': 'ArmchairIcon',
  '🎇': 'ArrowBigDown',
  '🎈': 'ArrowBigDownDash',
  '🎊': 'ArrowBigDownDashIcon',
  '🎋': 'ArrowBigDownIcon',
  '🎌': 'ArrowBigLeft',
  '🎍': 'ArrowBigLeftDash',
  '🎎': 'ArrowBigLeftDashIcon',
  '🎏': 'ArrowBigLeftIcon',
  '🎐': 'ArrowBigRight',
  '🎑': 'ArrowBigRightDash',
  '🎒': 'ArrowBigRightDashIcon',
  '🎓': 'ArrowBigRightIcon',
  '🎔': 'ArrowBigUp',
  '🎕': 'ArrowBigUpDash',
  '🎖': 'ArrowBigUpDashIcon',
  '🎗': 'ArrowBigUpIcon',
  '🎘': 'ArrowDown01',
  '🎙': 'ArrowDown01Icon',
  '🎚': 'ArrowDown10',
  '🎛': 'ArrowDown10Icon',
  '🎜': 'ArrowDownAZ',
  '🎝': 'ArrowDownAZIcon',
  '🎞': 'ArrowDownAz',
  '🎟': 'ArrowDownAzIcon',
  '🎠': 'ArrowDownCircle',
  '🎡': 'ArrowDownCircleIcon',
  '🎢': 'ArrowDownFromLine',
  '🎣': 'ArrowDownFromLineIcon',
  '🎥': 'ArrowDownIcon',
  '🎦': 'ArrowDownLeft',
  '🎩': 'ArrowDownLeftFromCircle',
  '🎪': 'ArrowDownLeftFromCircleIcon',
  '🎭': 'ArrowDownLeftFromSquare',
  '🎰': 'ArrowDownLeftFromSquareIcon',
  '🎱': 'ArrowDownLeftIcon',
  '🎲': 'ArrowDownLeftSquare',
  '🎳': 'ArrowDownLeftSquareIcon',
  '🎴': 'ArrowDownNarrowWide',
  '🎶': 'ArrowDownNarrowWideIcon',
  '🎷': 'ArrowDownRight',
  '🎸': 'ArrowDownRightFromCircle',
  '🎹': 'ArrowDownRightFromCircleIcon',
  '🎺': 'ArrowDownRightFromSquare',
  '🎻': 'ArrowDownRightFromSquareIcon',
  '🎼': 'ArrowDownRightIcon',
  '🎽': 'ArrowDownRightSquare',
  '🎾': 'ArrowDownRightSquareIcon',
  '🎿': 'ArrowDownSquare',
  '🏀': 'ArrowDownSquareIcon',
  '🏁': 'ArrowDownToDot',
  '🏂': 'ArrowDownToDotIcon',
  '🏃': 'ArrowDownToLine',
  '🏄': 'ArrowDownToLineIcon',
  '🏅': 'ArrowDownUp',
  '🏇': 'ArrowDownUpIcon',
  '🏈': 'ArrowDownWideNarrow',
  '🏉': 'ArrowDownWideNarrowIcon',
  '🏊': 'ArrowDownZA',
  '🏋': 'ArrowDownZAIcon',
  '🏌': 'ArrowDownZa',
  '🏍': 'ArrowDownZaIcon',
  '🏎': 'ArrowLeftCircle',
  '🏏': 'ArrowLeftCircleIcon',
  '🏐': 'ArrowLeftFromLine',
  '🏑': 'ArrowLeftFromLineIcon',
  '🏒': 'ArrowLeftIcon',
  '🏓': 'ArrowLeftRight',
  '🏔': 'ArrowLeftRightIcon',
  '🏕': 'ArrowLeftSquare',
  '🏖': 'ArrowLeftSquareIcon',
  '🏗': 'ArrowLeftToLine',
  '🏘': 'ArrowLeftToLineIcon',
  '🏙': 'ArrowRightCircle',
  '🏚': 'ArrowRightCircleIcon',
  '🏛': 'ArrowRightFromLine',
  '🏜': 'ArrowRightFromLineIcon',
};

const TABLER_MAP: Record<string, string> = {
  "Server": "server",
  "HardDrive": "database",
  "Cpu": "cpu",
  "Database": "database",
  "Terminal": "terminal-2",
  "Code": "code",
  "GitBranch": "git-branch",
  "GitCommit": "git-commit",
  "GitPullRequest": "git-pull-request",
  "Container": "box",
  "Bot": "robot",
  "Monitor": "device-desktop",
  "Laptop": "device-laptop",
  "Smartphone": "device-mobile",
  "Tablet": "device-tablet",
  "Cloud": "cloud",
  "CloudUpload": "cloud-upload",
  "CloudDownload": "cloud-download",
  "Wifi": "wifi",
  "Router": "router",
  "Radio": "radio",
  "Satellite": "satellite",
  "Plug": "plug",
  "Battery": "battery-charging",
  "Save": "device-floppy",
  "Printer": "printer",
  "Keyboard": "keyboard",
  "Mouse": "mouse",
  "Watch": "device-watch",
  "Tv": "device-tv",
  "Gamepad": "device-gamepad",
  "Gamepad2": "device-gamepad-2",
  "Disc": "disc",
  "Binary": "binary",
  "Scan": "scan",
  "Shield": "shield",
  "ShieldAlert": "shield-exclamation",
  "ShieldCheck": "shield-check",
  "Lock": "lock",
  "Unlock": "lock-open",
  "Key": "key",
  "Bug": "bug",
  "FlaskConical": "flask",
  "Flame": "flame",
  "Activity": "activity",
  "Globe": "world",
  "Network": "network",
  "Folder": "folder",
  "FolderOpen": "folder-open",
  "FolderPlus": "folder-plus",
  "File": "file",
  "FileText": "file-text",
  "FileCode": "file-code",
  "Files": "files",
  "Archive": "archive",
  "Clipboard": "clipboard",
  "Book": "book",
  "BookOpen": "book",
  "Bookmark": "bookmark",
  "Tag": "tag",
  "Paperclip": "paperclip",
  "PenTool": "pencil",
  "Pencil": "pencil",
  "Palette": "palette",
  "Camera": "camera",
  "Video": "video",
  "Film": "film",
  "Clapperboard": "movie",
  "Mic": "microphone",
  "MicOff": "microphone-off",
  "Headphones": "headphones",
  "Music": "music",
  "Volume2": "volume",
  "VolumeX": "volume-3",
  "Sliders": "sliders",
  "Image": "photo",
  "Newspaper": "news",
  "BarChart": "chart-bar",
  "BarChart2": "chart-bar",
  "PieChart": "chart-pie",
  "Check": "check",
  "X": "x",
  "XCircle": "circle-x",
  "Minus": "minus",
  "HelpCircle": "help",
  "AlertCircle": "alert-circle",
  "AlertTriangle": "alert-triangle",
  "Info": "info-circle",
  "Settings": "settings",
  "Wrench": "wrench",
  "Hammer": "hammer",
  "Menu": "menu-2",
  "MoreHorizontal": "dots",
  "MoreVertical": "dots-vertical",
  "Grid": "grid-dots",
  "Layout": "layout",
  "Eye": "eye",
  "EyeOff": "eye-off",
  "Sun": "sun",
  "Moon": "moon",
  "Sparkles": "sparkles",
  "Star": "star",
  "Heart": "heart",
  "Smile": "mood-smile",
  "Frown": "mood-sad",
  "ThumbsUp": "thumb-up",
  "ThumbsDown": "thumb-down",
  "User": "user",
  "Users": "users",
  "LogIn": "login",
  "ArrowLeft": "arrow-left",
  "ArrowRight": "arrow-right",
  "ArrowUp": "arrow-up",
  "ArrowDown": "arrow-down",
  "ChevronLeft": "chevron-left",
  "ChevronRight": "chevron-right",
  "ChevronUp": "chevron-up",
  "ChevronDown": "chevron-down",
  "RefreshCw": "refresh",
  "RotateCw": "rotate-clockwise",
  "RotateCcw": "rotate",
  "ExternalLink": "external-link",
  "Unlink": "unlink",
  "Share2": "share",
  "Send": "send",
  "Mail": "mail",
  "Inbox": "inbox",
  "Bell": "bell",
  "BellOff": "bell-off",
  "Home": "home",
  "Building": "building",
  "Building2": "building-factory",
  "Construction": "crane",
  "Bed": "bed",
  "Bath": "bath",
  "ShowerHead": "shower",
  "Droplet": "droplet",
  "Waves": "waves",
  "Snowflake": "snowflake",
  "Wind": "wind",
  "Compass": "compass",
  "Map": "map",
  "Navigation": "navigation",
  "Anchor": "anchor",
  "Car": "car",
  "Truck": "truck",
  "Bus": "bus",
  "Bike": "bike",
  "Plane": "plane",
  "Ship": "ship",
  "Briefcase": "briefcase",
  "ShoppingBag": "shopping-bag",
  "ShoppingCart": "shopping-cart",
  "CreditCard": "credit-card",
  "DollarSign": "currency-dollar",
  "Euro": "currency-euro",
  "Gift": "gift",
  "Trophy": "trophy",
  "Award": "award",
  "Medal": "medal",
  "Crown": "crown",
  "Target": "target",
  "Clock": "clock",
  "Calendar": "calendar",
  "Timer": "timer",
  "Hourglass": "hourglass",
  "Scale": "scale",
  "Scissors": "scissors",
  "Box": "box",
  "Layers": "layers-subtract",
  "Coffee": "cup",
  "Utensils": "utensils",
  "Pizza": "pizza",
  "SunDim": "sun-high",
  "CloudSun": "cloud-sun",
  "CloudRain": "cloud-rain",
  "Trees": "trees",
  "Sprout": "plant",
  "Apple": "apple",
  "Cat": "cat",
  "Dog": "dog",
  "Rabbit": "rabbit",
  "Squirrel": "squirrel",
  "Bird": "bird",
  "Fish": "fish",
  "Turtle": "turtle",
  "Snail": "snail",
  "Lightbulb": "bulb",
  "Glasses": "glasses",
  "Ticket": "ticket",
  "PartyPopper": "confetti",
  "Trash": "trash",
  "Upload": "upload",
  "TerminalSquare": "terminal",
  "FileCheck": "file-check",
  "Globe2": "world",
  "Pin": "pin",
  "HeartOff": "heart-off",
  "LockKeyhole": "lock-access",
  "FileSearch": "file-search",
  "AArrowDown": "aarrow-down",
  "AArrowDownIcon": "aarrow-down-icon",
  "AArrowUp": "aarrow-up",
  "AArrowUpIcon": "aarrow-up-icon",
  "ALargeSmall": "alarge-small",
  "ALargeSmallIcon": "alarge-small-icon",
  "Accessibility": "accessibility",
  "AccessibilityIcon": "accessibility-icon",
  "ActivityIcon": "activity-icon",
  "ActivitySquare": "activity-square",
  "ActivitySquareIcon": "activity-square-icon",
  "AirVent": "air-vent",
  "AirVentIcon": "air-vent-icon",
  "Airplay": "airplay",
  "AirplayIcon": "airplay-icon",
  "AlarmCheck": "alarm-check",
  "AlarmCheckIcon": "alarm-check-icon",
  "AlarmClock": "alarm-clock",
  "AlarmClockCheck": "alarm-clock-check",
  "AlarmClockCheckIcon": "alarm-clock-check-icon",
  "AlarmClockIcon": "alarm-clock-icon",
  "AlarmClockMinus": "alarm-clock-minus",
  "AlarmClockMinusIcon": "alarm-clock-minus-icon",
  "AlarmClockOff": "alarm-clock-off",
  "AlarmClockOffIcon": "alarm-clock-off-icon",
  "AlarmClockPlus": "alarm-clock-plus",
  "AlarmClockPlusIcon": "alarm-clock-plus-icon",
  "AlarmMinus": "alarm-minus",
  "AlarmMinusIcon": "alarm-minus-icon",
  "AlarmPlus": "alarm-plus",
  "AlarmPlusIcon": "alarm-plus-icon",
  "AlarmSmoke": "alarm-smoke",
  "AlarmSmokeIcon": "alarm-smoke-icon",
  "Album": "album",
  "AlbumIcon": "album-icon",
  "AlertCircleIcon": "alert-circle-icon",
  "AlertOctagon": "alert-octagon",
  "AlertOctagonIcon": "alert-octagon-icon",
  "AlertTriangleIcon": "alert-triangle-icon",
  "AlignCenter": "align-center",
  "AlignCenterHorizontal": "align-center-horizontal",
  "AlignCenterHorizontalIcon": "align-center-horizontal-icon",
  "AlignCenterIcon": "align-center-icon",
  "AlignCenterVertical": "align-center-vertical",
  "AlignCenterVerticalIcon": "align-center-vertical-icon",
  "AlignEndHorizontal": "align-end-horizontal",
  "AlignEndHorizontalIcon": "align-end-horizontal-icon",
  "AlignEndVertical": "align-end-vertical",
  "AlignEndVerticalIcon": "align-end-vertical-icon",
  "AlignHorizontalDistributeCenter": "align-horizontal-distribute-center",
  "AlignHorizontalDistributeCenterIcon": "align-horizontal-distribute-center-icon",
  "AlignHorizontalDistributeEnd": "align-horizontal-distribute-end",
  "AlignHorizontalDistributeEndIcon": "align-horizontal-distribute-end-icon",
  "AlignHorizontalDistributeStart": "align-horizontal-distribute-start",
  "AlignHorizontalDistributeStartIcon": "align-horizontal-distribute-start-icon",
  "AlignHorizontalJustifyCenter": "align-horizontal-justify-center",
  "AlignHorizontalJustifyCenterIcon": "align-horizontal-justify-center-icon",
  "AlignHorizontalJustifyEnd": "align-horizontal-justify-end",
  "AlignHorizontalJustifyEndIcon": "align-horizontal-justify-end-icon",
  "AlignHorizontalJustifyStart": "align-horizontal-justify-start",
  "AlignHorizontalJustifyStartIcon": "align-horizontal-justify-start-icon",
  "AlignHorizontalSpaceAround": "align-horizontal-space-around",
  "AlignHorizontalSpaceAroundIcon": "align-horizontal-space-around-icon",
  "AlignHorizontalSpaceBetween": "align-horizontal-space-between",
  "AlignHorizontalSpaceBetweenIcon": "align-horizontal-space-between-icon",
  "AlignJustify": "align-justify",
  "AlignJustifyIcon": "align-justify-icon",
  "AlignLeft": "align-left",
  "AlignLeftIcon": "align-left-icon",
  "AlignRight": "align-right",
  "AlignRightIcon": "align-right-icon",
  "AlignStartHorizontal": "align-start-horizontal",
  "AlignStartHorizontalIcon": "align-start-horizontal-icon",
  "AlignStartVertical": "align-start-vertical",
  "AlignStartVerticalIcon": "align-start-vertical-icon",
  "AlignVerticalDistributeCenter": "align-vertical-distribute-center",
  "AlignVerticalDistributeCenterIcon": "align-vertical-distribute-center-icon",
  "AlignVerticalDistributeEnd": "align-vertical-distribute-end",
  "AlignVerticalDistributeEndIcon": "align-vertical-distribute-end-icon",
  "AlignVerticalDistributeStart": "align-vertical-distribute-start",
  "AlignVerticalDistributeStartIcon": "align-vertical-distribute-start-icon",
  "AlignVerticalJustifyCenter": "align-vertical-justify-center",
  "AlignVerticalJustifyCenterIcon": "align-vertical-justify-center-icon",
  "AlignVerticalJustifyEnd": "align-vertical-justify-end",
  "AlignVerticalJustifyEndIcon": "align-vertical-justify-end-icon",
  "AlignVerticalJustifyStart": "align-vertical-justify-start",
  "AlignVerticalJustifyStartIcon": "align-vertical-justify-start-icon",
  "AlignVerticalSpaceAround": "align-vertical-space-around",
  "AlignVerticalSpaceAroundIcon": "align-vertical-space-around-icon",
  "AlignVerticalSpaceBetween": "align-vertical-space-between",
  "AlignVerticalSpaceBetweenIcon": "align-vertical-space-between-icon",
  "Ambulance": "ambulance",
  "AmbulanceIcon": "ambulance-icon",
  "Ampersand": "ampersand",
  "AmpersandIcon": "ampersand-icon",
  "Ampersands": "ampersands",
  "AmpersandsIcon": "ampersands-icon",
  "Amphora": "amphora",
  "AmphoraIcon": "amphora-icon",
  "AnchorIcon": "anchor-icon",
  "Angry": "angry",
  "AngryIcon": "angry-icon",
  "Annoyed": "annoyed",
  "AnnoyedIcon": "annoyed-icon",
  "Antenna": "antenna",
  "AntennaIcon": "antenna-icon",
  "Anvil": "anvil",
  "AnvilIcon": "anvil-icon",
  "Aperture": "aperture",
  "ApertureIcon": "aperture-icon",
  "AppWindow": "app-window",
  "AppWindowIcon": "app-window-icon",
  "AppWindowMac": "app-window-mac",
  "AppWindowMacIcon": "app-window-mac-icon",
  "AppleIcon": "apple-icon",
  "ArchiveIcon": "archive-icon",
  "ArchiveRestore": "archive-restore",
  "ArchiveRestoreIcon": "archive-restore-icon",
  "ArchiveX": "archive-x",
  "ArchiveXIcon": "archive-xicon",
  "AreaChart": "area-chart",
  "AreaChartIcon": "area-chart-icon",
  "Armchair": "armchair",
  "ArmchairIcon": "armchair-icon",
  "ArrowBigDown": "arrow-big-down",
  "ArrowBigDownDash": "arrow-big-down-dash",
  "ArrowBigDownDashIcon": "arrow-big-down-dash-icon",
  "ArrowBigDownIcon": "arrow-big-down-icon",
  "ArrowBigLeft": "arrow-big-left",
  "ArrowBigLeftDash": "arrow-big-left-dash",
  "ArrowBigLeftDashIcon": "arrow-big-left-dash-icon",
  "ArrowBigLeftIcon": "arrow-big-left-icon",
  "ArrowBigRight": "arrow-big-right",
  "ArrowBigRightDash": "arrow-big-right-dash",
  "ArrowBigRightDashIcon": "arrow-big-right-dash-icon",
  "ArrowBigRightIcon": "arrow-big-right-icon",
  "ArrowBigUp": "arrow-big-up",
  "ArrowBigUpDash": "arrow-big-up-dash",
  "ArrowBigUpDashIcon": "arrow-big-up-dash-icon",
  "ArrowBigUpIcon": "arrow-big-up-icon",
  "ArrowDown01": "arrow-down01",
  "ArrowDown01Icon": "arrow-down01-icon",
  "ArrowDown10": "arrow-down10",
  "ArrowDown10Icon": "arrow-down10-icon",
  "ArrowDownAZ": "arrow-down-az",
  "ArrowDownAZIcon": "arrow-down-azicon",
  "ArrowDownAz": "arrow-down-az",
  "ArrowDownAzIcon": "arrow-down-az-icon",
  "ArrowDownCircle": "arrow-down-circle",
  "ArrowDownCircleIcon": "arrow-down-circle-icon",
  "ArrowDownFromLine": "arrow-down-from-line",
  "ArrowDownFromLineIcon": "arrow-down-from-line-icon",
  "ArrowDownIcon": "arrow-down-icon",
  "ArrowDownLeft": "arrow-down-left",
  "ArrowDownLeftFromCircle": "arrow-down-left-from-circle",
  "ArrowDownLeftFromCircleIcon": "arrow-down-left-from-circle-icon",
  "ArrowDownLeftFromSquare": "arrow-down-left-from-square",
  "ArrowDownLeftFromSquareIcon": "arrow-down-left-from-square-icon",
  "ArrowDownLeftIcon": "arrow-down-left-icon",
  "ArrowDownLeftSquare": "arrow-down-left-square",
  "ArrowDownLeftSquareIcon": "arrow-down-left-square-icon",
  "ArrowDownNarrowWide": "arrow-down-narrow-wide",
  "ArrowDownNarrowWideIcon": "arrow-down-narrow-wide-icon",
  "ArrowDownRight": "arrow-down-right",
  "ArrowDownRightFromCircle": "arrow-down-right-from-circle",
  "ArrowDownRightFromCircleIcon": "arrow-down-right-from-circle-icon",
  "ArrowDownRightFromSquare": "arrow-down-right-from-square",
  "ArrowDownRightFromSquareIcon": "arrow-down-right-from-square-icon",
  "ArrowDownRightIcon": "arrow-down-right-icon",
  "ArrowDownRightSquare": "arrow-down-right-square",
  "ArrowDownRightSquareIcon": "arrow-down-right-square-icon",
  "ArrowDownSquare": "arrow-down-square",
  "ArrowDownSquareIcon": "arrow-down-square-icon",
  "ArrowDownToDot": "arrow-down-to-dot",
  "ArrowDownToDotIcon": "arrow-down-to-dot-icon",
  "ArrowDownToLine": "arrow-down-to-line",
  "ArrowDownToLineIcon": "arrow-down-to-line-icon",
  "ArrowDownUp": "arrow-down-up",
  "ArrowDownUpIcon": "arrow-down-up-icon",
  "ArrowDownWideNarrow": "arrow-down-wide-narrow",
  "ArrowDownWideNarrowIcon": "arrow-down-wide-narrow-icon",
  "ArrowDownZA": "arrow-down-za",
  "ArrowDownZAIcon": "arrow-down-zaicon",
  "ArrowDownZa": "arrow-down-za",
  "ArrowDownZaIcon": "arrow-down-za-icon",
  "ArrowLeftCircle": "arrow-left-circle",
  "ArrowLeftCircleIcon": "arrow-left-circle-icon",
  "ArrowLeftFromLine": "arrow-left-from-line",
  "ArrowLeftFromLineIcon": "arrow-left-from-line-icon",
  "ArrowLeftIcon": "arrow-left-icon",
  "ArrowLeftRight": "arrow-left-right",
  "ArrowLeftRightIcon": "arrow-left-right-icon",
  "ArrowLeftSquare": "arrow-left-square",
  "ArrowLeftSquareIcon": "arrow-left-square-icon",
  "ArrowLeftToLine": "arrow-left-to-line",
  "ArrowLeftToLineIcon": "arrow-left-to-line-icon",
  "ArrowRightCircle": "arrow-right-circle",
  "ArrowRightCircleIcon": "arrow-right-circle-icon",
  "ArrowRightFromLine": "arrow-right-from-line",
  "ArrowRightFromLineIcon": "arrow-right-from-line-icon"
};
const BOOTSTRAP_MAP: Record<string, string> = {
  "Server": "hdd-stack",
  "HardDrive": "hdd",
  "Cpu": "cpu",
  "Database": "database",
  "Terminal": "terminal",
  "Code": "code-slash",
  "GitBranch": "diagram-2",
  "GitCommit": "record-circle",
  "GitPullRequest": "git",
  "Container": "box",
  "Bot": "robot",
  "Monitor": "display",
  "Laptop": "laptop",
  "Smartphone": "phone",
  "Tablet": "tablet",
  "Cloud": "cloud",
  "CloudUpload": "cloud-upload",
  "CloudDownload": "cloud-download",
  "Wifi": "wifi",
  "Router": "router",
  "Radio": "broadcast",
  "Satellite": "globe",
  "Plug": "plug",
  "Battery": "battery-charging",
  "Save": "floppy",
  "Printer": "printer",
  "Keyboard": "keyboard",
  "Mouse": "mouse",
  "Watch": "stopwatch",
  "Tv": "tv",
  "Gamepad": "controller",
  "Gamepad2": "controller",
  "Disc": "disc",
  "Binary": "code",
  "Scan": "upc-scan",
  "Shield": "shield",
  "ShieldAlert": "shield-exclamation",
  "ShieldCheck": "shield-check",
  "Lock": "lock",
  "Unlock": "unlock",
  "Key": "key",
  "Bug": "bug",
  "FlaskConical": "beaker",
  "Flame": "fire",
  "Activity": "activity",
  "Globe": "globe",
  "Network": "diagram-3",
  "Folder": "folder",
  "FolderOpen": "folder2-open",
  "FolderPlus": "folder-plus",
  "File": "file",
  "FileText": "file-earmark-text",
  "FileCode": "file-earmark-code",
  "Files": "files",
  "Archive": "archive",
  "Clipboard": "clipboard",
  "Book": "book",
  "BookOpen": "book-half",
  "Bookmark": "bookmark",
  "Tag": "tag",
  "Paperclip": "paperclip",
  "PenTool": "pen",
  "Pencil": "pencil",
  "Palette": "palette",
  "Camera": "camera",
  "Video": "camera-video",
  "Film": "film",
  "Clapperboard": "film",
  "Mic": "mic",
  "MicOff": "mic-mute",
  "Headphones": "headphones",
  "Music": "music-note",
  "Volume2": "volume-up",
  "VolumeX": "volume-mute",
  "Sliders": "sliders",
  "Image": "image",
  "Newspaper": "newspaper",
  "BarChart": "bar-chart",
  "BarChart2": "bar-chart-line",
  "PieChart": "pie-chart",
  "Check": "check",
  "X": "x",
  "XCircle": "x-circle",
  "Minus": "dash",
  "HelpCircle": "question-circle",
  "AlertCircle": "exclamation-circle",
  "AlertTriangle": "exclamation-triangle",
  "Info": "info-circle",
  "Settings": "gear",
  "Wrench": "wrench",
  "Hammer": "hammer",
  "Menu": "list",
  "MoreHorizontal": "three-dots",
  "MoreVertical": "three-dots-vertical",
  "Grid": "grid",
  "Layout": "layout-split",
  "Eye": "eye",
  "EyeOff": "eye-slash",
  "Sun": "sun",
  "Moon": "moon",
  "Sparkles": "stars",
  "Star": "star",
  "Heart": "heart",
  "Smile": "emoji-smile",
  "Frown": "emoji-frown",
  "ThumbsUp": "hand-thumbs-up",
  "ThumbsDown": "hand-thumbs-down",
  "User": "person",
  "Users": "people",
  "LogIn": "box-arrow-in-right",
  "ArrowLeft": "arrow-left",
  "ArrowRight": "arrow-right",
  "ArrowUp": "arrow-up",
  "ArrowDown": "arrow-down",
  "ChevronLeft": "chevron-left",
  "ChevronRight": "chevron-right",
  "ChevronUp": "chevron-up",
  "ChevronDown": "chevron-down",
  "RefreshCw": "arrow-repeat",
  "RotateCw": "arrow-clockwise",
  "RotateCcw": "arrow-counterclockwise",
  "ExternalLink": "box-arrow-up-right",
  "Unlink": "link",
  "Share2": "share",
  "Send": "send",
  "Mail": "envelope",
  "Inbox": "inbox",
  "Bell": "bell",
  "BellOff": "bell-slash",
  "Home": "house",
  "Building": "building",
  "Building2": "buildings",
  "Construction": "tools",
  "Bed": "hospital",
  "Bath": "droplet",
  "ShowerHead": "droplet-half",
  "Droplet": "droplet",
  "Waves": "tsunami",
  "Snowflake": "snow",
  "Wind": "wind",
  "Compass": "compass",
  "Map": "map",
  "Navigation": "compass",
  "Anchor": "anchor",
  "Car": "car-front",
  "Truck": "truck",
  "Bus": "bus-front",
  "Bike": "bicycle",
  "Plane": "airplane",
  "Ship": "water",
  "Briefcase": "briefcase",
  "ShoppingBag": "bag",
  "ShoppingCart": "cart",
  "CreditCard": "credit-card",
  "DollarSign": "currency-dollar",
  "Euro": "currency-euro",
  "Gift": "gift",
  "Trophy": "trophy",
  "Award": "award",
  "Medal": "medal",
  "Crown": "badge-3d",
  "Target": "bullseye",
  "Clock": "clock",
  "Calendar": "calendar",
  "Timer": "stopwatch",
  "Hourglass": "hourglass",
  "Scale": "scale",
  "Scissors": "scissors",
  "Box": "box",
  "Layers": "layers",
  "Coffee": "cup-hot",
  "Utensils": "utensils",
  "Pizza": "pie-chart",
  "SunDim": "sun",
  "CloudSun": "cloud-sun",
  "CloudRain": "cloud-rain",
  "Trees": "tree",
  "Sprout": "flower1",
  "Apple": "apple",
  "Cat": "github",
  "Dog": "emoji-smile",
  "Rabbit": "emoji-smile",
  "Squirrel": "emoji-smile",
  "Bird": "twitter",
  "Fish": "water",
  "Turtle": "emoji-smile",
  "Snail": "emoji-smile",
  "Lightbulb": "lightbulb",
  "Glasses": "glasses",
  "Ticket": "ticket-perforated",
  "PartyPopper": "balloon",
  "Trash": "trash",
  "Upload": "upload",
  "TerminalSquare": "terminal-fill",
  "FileCheck": "file-earmark-check",
  "Globe2": "globe2",
  "Pin": "pin",
  "HeartOff": "heartbreak",
  "LockKeyhole": "lock-fill",
  "FileSearch": "file-earmark-search",
  "AArrowDown": "aarrow-down",
  "AArrowDownIcon": "aarrow-down-icon",
  "AArrowUp": "aarrow-up",
  "AArrowUpIcon": "aarrow-up-icon",
  "ALargeSmall": "alarge-small",
  "ALargeSmallIcon": "alarge-small-icon",
  "Accessibility": "accessibility",
  "AccessibilityIcon": "accessibility-icon",
  "ActivityIcon": "activity-icon",
  "ActivitySquare": "activity-square",
  "ActivitySquareIcon": "activity-square-icon",
  "AirVent": "air-vent",
  "AirVentIcon": "air-vent-icon",
  "Airplay": "airplay",
  "AirplayIcon": "airplay-icon",
  "AlarmCheck": "alarm-check",
  "AlarmCheckIcon": "alarm-check-icon",
  "AlarmClock": "alarm-clock",
  "AlarmClockCheck": "alarm-clock-check",
  "AlarmClockCheckIcon": "alarm-clock-check-icon",
  "AlarmClockIcon": "alarm-clock-icon",
  "AlarmClockMinus": "alarm-clock-minus",
  "AlarmClockMinusIcon": "alarm-clock-minus-icon",
  "AlarmClockOff": "alarm-clock-off",
  "AlarmClockOffIcon": "alarm-clock-off-icon",
  "AlarmClockPlus": "alarm-clock-plus",
  "AlarmClockPlusIcon": "alarm-clock-plus-icon",
  "AlarmMinus": "alarm-minus",
  "AlarmMinusIcon": "alarm-minus-icon",
  "AlarmPlus": "alarm-plus",
  "AlarmPlusIcon": "alarm-plus-icon",
  "AlarmSmoke": "alarm-smoke",
  "AlarmSmokeIcon": "alarm-smoke-icon",
  "Album": "album",
  "AlbumIcon": "album-icon",
  "AlertCircleIcon": "alert-circle-icon",
  "AlertOctagon": "alert-octagon",
  "AlertOctagonIcon": "alert-octagon-icon",
  "AlertTriangleIcon": "alert-triangle-icon",
  "AlignCenter": "align-center",
  "AlignCenterHorizontal": "align-center-horizontal",
  "AlignCenterHorizontalIcon": "align-center-horizontal-icon",
  "AlignCenterIcon": "align-center-icon",
  "AlignCenterVertical": "align-center-vertical",
  "AlignCenterVerticalIcon": "align-center-vertical-icon",
  "AlignEndHorizontal": "align-end-horizontal",
  "AlignEndHorizontalIcon": "align-end-horizontal-icon",
  "AlignEndVertical": "align-end-vertical",
  "AlignEndVerticalIcon": "align-end-vertical-icon",
  "AlignHorizontalDistributeCenter": "align-horizontal-distribute-center",
  "AlignHorizontalDistributeCenterIcon": "align-horizontal-distribute-center-icon",
  "AlignHorizontalDistributeEnd": "align-horizontal-distribute-end",
  "AlignHorizontalDistributeEndIcon": "align-horizontal-distribute-end-icon",
  "AlignHorizontalDistributeStart": "align-horizontal-distribute-start",
  "AlignHorizontalDistributeStartIcon": "align-horizontal-distribute-start-icon",
  "AlignHorizontalJustifyCenter": "align-horizontal-justify-center",
  "AlignHorizontalJustifyCenterIcon": "align-horizontal-justify-center-icon",
  "AlignHorizontalJustifyEnd": "align-horizontal-justify-end",
  "AlignHorizontalJustifyEndIcon": "align-horizontal-justify-end-icon",
  "AlignHorizontalJustifyStart": "align-horizontal-justify-start",
  "AlignHorizontalJustifyStartIcon": "align-horizontal-justify-start-icon",
  "AlignHorizontalSpaceAround": "align-horizontal-space-around",
  "AlignHorizontalSpaceAroundIcon": "align-horizontal-space-around-icon",
  "AlignHorizontalSpaceBetween": "align-horizontal-space-between",
  "AlignHorizontalSpaceBetweenIcon": "align-horizontal-space-between-icon",
  "AlignJustify": "align-justify",
  "AlignJustifyIcon": "align-justify-icon",
  "AlignLeft": "align-left",
  "AlignLeftIcon": "align-left-icon",
  "AlignRight": "align-right",
  "AlignRightIcon": "align-right-icon",
  "AlignStartHorizontal": "align-start-horizontal",
  "AlignStartHorizontalIcon": "align-start-horizontal-icon",
  "AlignStartVertical": "align-start-vertical",
  "AlignStartVerticalIcon": "align-start-vertical-icon",
  "AlignVerticalDistributeCenter": "align-vertical-distribute-center",
  "AlignVerticalDistributeCenterIcon": "align-vertical-distribute-center-icon",
  "AlignVerticalDistributeEnd": "align-vertical-distribute-end",
  "AlignVerticalDistributeEndIcon": "align-vertical-distribute-end-icon",
  "AlignVerticalDistributeStart": "align-vertical-distribute-start",
  "AlignVerticalDistributeStartIcon": "align-vertical-distribute-start-icon",
  "AlignVerticalJustifyCenter": "align-vertical-justify-center",
  "AlignVerticalJustifyCenterIcon": "align-vertical-justify-center-icon",
  "AlignVerticalJustifyEnd": "align-vertical-justify-end",
  "AlignVerticalJustifyEndIcon": "align-vertical-justify-end-icon",
  "AlignVerticalJustifyStart": "align-vertical-justify-start",
  "AlignVerticalJustifyStartIcon": "align-vertical-justify-start-icon",
  "AlignVerticalSpaceAround": "align-vertical-space-around",
  "AlignVerticalSpaceAroundIcon": "align-vertical-space-around-icon",
  "AlignVerticalSpaceBetween": "align-vertical-space-between",
  "AlignVerticalSpaceBetweenIcon": "align-vertical-space-between-icon",
  "Ambulance": "ambulance",
  "AmbulanceIcon": "ambulance-icon",
  "Ampersand": "ampersand",
  "AmpersandIcon": "ampersand-icon",
  "Ampersands": "ampersands",
  "AmpersandsIcon": "ampersands-icon",
  "Amphora": "amphora",
  "AmphoraIcon": "amphora-icon",
  "AnchorIcon": "anchor-icon",
  "Angry": "angry",
  "AngryIcon": "angry-icon",
  "Annoyed": "annoyed",
  "AnnoyedIcon": "annoyed-icon",
  "Antenna": "antenna",
  "AntennaIcon": "antenna-icon",
  "Anvil": "anvil",
  "AnvilIcon": "anvil-icon",
  "Aperture": "aperture",
  "ApertureIcon": "aperture-icon",
  "AppWindow": "app-window",
  "AppWindowIcon": "app-window-icon",
  "AppWindowMac": "app-window-mac",
  "AppWindowMacIcon": "app-window-mac-icon",
  "AppleIcon": "apple-icon",
  "ArchiveIcon": "archive-icon",
  "ArchiveRestore": "archive-restore",
  "ArchiveRestoreIcon": "archive-restore-icon",
  "ArchiveX": "archive-x",
  "ArchiveXIcon": "archive-xicon",
  "AreaChart": "area-chart",
  "AreaChartIcon": "area-chart-icon",
  "Armchair": "armchair",
  "ArmchairIcon": "armchair-icon",
  "ArrowBigDown": "arrow-big-down",
  "ArrowBigDownDash": "arrow-big-down-dash",
  "ArrowBigDownDashIcon": "arrow-big-down-dash-icon",
  "ArrowBigDownIcon": "arrow-big-down-icon",
  "ArrowBigLeft": "arrow-big-left",
  "ArrowBigLeftDash": "arrow-big-left-dash",
  "ArrowBigLeftDashIcon": "arrow-big-left-dash-icon",
  "ArrowBigLeftIcon": "arrow-big-left-icon",
  "ArrowBigRight": "arrow-big-right",
  "ArrowBigRightDash": "arrow-big-right-dash",
  "ArrowBigRightDashIcon": "arrow-big-right-dash-icon",
  "ArrowBigRightIcon": "arrow-big-right-icon",
  "ArrowBigUp": "arrow-big-up",
  "ArrowBigUpDash": "arrow-big-up-dash",
  "ArrowBigUpDashIcon": "arrow-big-up-dash-icon",
  "ArrowBigUpIcon": "arrow-big-up-icon",
  "ArrowDown01": "arrow-down01",
  "ArrowDown01Icon": "arrow-down01-icon",
  "ArrowDown10": "arrow-down10",
  "ArrowDown10Icon": "arrow-down10-icon",
  "ArrowDownAZ": "arrow-down-az",
  "ArrowDownAZIcon": "arrow-down-azicon",
  "ArrowDownAz": "arrow-down-az",
  "ArrowDownAzIcon": "arrow-down-az-icon",
  "ArrowDownCircle": "arrow-down-circle",
  "ArrowDownCircleIcon": "arrow-down-circle-icon",
  "ArrowDownFromLine": "arrow-down-from-line",
  "ArrowDownFromLineIcon": "arrow-down-from-line-icon",
  "ArrowDownIcon": "arrow-down-icon",
  "ArrowDownLeft": "arrow-down-left",
  "ArrowDownLeftFromCircle": "arrow-down-left-from-circle",
  "ArrowDownLeftFromCircleIcon": "arrow-down-left-from-circle-icon",
  "ArrowDownLeftFromSquare": "arrow-down-left-from-square",
  "ArrowDownLeftFromSquareIcon": "arrow-down-left-from-square-icon",
  "ArrowDownLeftIcon": "arrow-down-left-icon",
  "ArrowDownLeftSquare": "arrow-down-left-square",
  "ArrowDownLeftSquareIcon": "arrow-down-left-square-icon",
  "ArrowDownNarrowWide": "arrow-down-narrow-wide",
  "ArrowDownNarrowWideIcon": "arrow-down-narrow-wide-icon",
  "ArrowDownRight": "arrow-down-right",
  "ArrowDownRightFromCircle": "arrow-down-right-from-circle",
  "ArrowDownRightFromCircleIcon": "arrow-down-right-from-circle-icon",
  "ArrowDownRightFromSquare": "arrow-down-right-from-square",
  "ArrowDownRightFromSquareIcon": "arrow-down-right-from-square-icon",
  "ArrowDownRightIcon": "arrow-down-right-icon",
  "ArrowDownRightSquare": "arrow-down-right-square",
  "ArrowDownRightSquareIcon": "arrow-down-right-square-icon",
  "ArrowDownSquare": "arrow-down-square",
  "ArrowDownSquareIcon": "arrow-down-square-icon",
  "ArrowDownToDot": "arrow-down-to-dot",
  "ArrowDownToDotIcon": "arrow-down-to-dot-icon",
  "ArrowDownToLine": "arrow-down-to-line",
  "ArrowDownToLineIcon": "arrow-down-to-line-icon",
  "ArrowDownUp": "arrow-down-up",
  "ArrowDownUpIcon": "arrow-down-up-icon",
  "ArrowDownWideNarrow": "arrow-down-wide-narrow",
  "ArrowDownWideNarrowIcon": "arrow-down-wide-narrow-icon",
  "ArrowDownZA": "arrow-down-za",
  "ArrowDownZAIcon": "arrow-down-zaicon",
  "ArrowDownZa": "arrow-down-za",
  "ArrowDownZaIcon": "arrow-down-za-icon",
  "ArrowLeftCircle": "arrow-left-circle",
  "ArrowLeftCircleIcon": "arrow-left-circle-icon",
  "ArrowLeftFromLine": "arrow-left-from-line",
  "ArrowLeftFromLineIcon": "arrow-left-from-line-icon",
  "ArrowLeftIcon": "arrow-left-icon",
  "ArrowLeftRight": "arrow-left-right",
  "ArrowLeftRightIcon": "arrow-left-right-icon",
  "ArrowLeftSquare": "arrow-left-square",
  "ArrowLeftSquareIcon": "arrow-left-square-icon",
  "ArrowLeftToLine": "arrow-left-to-line",
  "ArrowLeftToLineIcon": "arrow-left-to-line-icon",
  "ArrowRightCircle": "arrow-right-circle",
  "ArrowRightCircleIcon": "arrow-right-circle-icon",
  "ArrowRightFromLine": "arrow-right-from-line",
  "ArrowRightFromLineIcon": "arrow-right-from-line-icon"
};
const MDI_MAP: Record<string, string> = {
  "Server": "server",
  "HardDrive": "harddisk",
  "Cpu": "cpu",
  "Database": "database",
  "Terminal": "console",
  "Code": "code-tags",
  "GitBranch": "source-branch",
  "GitCommit": "source-commit",
  "GitPullRequest": "source-pull",
  "Container": "cube-outline",
  "Bot": "robot",
  "Monitor": "monitor",
  "Laptop": "laptop",
  "Smartphone": "cellphone",
  "Tablet": "tablet",
  "Cloud": "cloud",
  "CloudUpload": "cloud-upload",
  "CloudDownload": "cloud-download",
  "Wifi": "wifi",
  "Router": "router",
  "Radio": "radio",
  "Satellite": "satellite-variant",
  "Plug": "power-plug",
  "Battery": "battery-charging",
  "Save": "content-save",
  "Printer": "printer",
  "Keyboard": "keyboard",
  "Mouse": "mouse",
  "Watch": "watch",
  "Tv": "television",
  "Gamepad": "gamepad",
  "Gamepad2": "gamepad-variant",
  "Disc": "disc",
  "Binary": "binary",
  "Scan": "qrcode-scan",
  "Shield": "shield",
  "ShieldAlert": "shield-alert",
  "ShieldCheck": "shield-check",
  "Lock": "lock",
  "Unlock": "lock-open",
  "Key": "key",
  "Bug": "bug",
  "FlaskConical": "flask",
  "Flame": "fire",
  "Activity": "pulse",
  "Globe": "earth",
  "Network": "network",
  "Folder": "folder",
  "FolderOpen": "folder-open",
  "FolderPlus": "folder-plus",
  "File": "file",
  "FileText": "file-document",
  "FileCode": "file-code",
  "Files": "file-multiple",
  "Archive": "archive",
  "Clipboard": "clipboard",
  "Book": "book",
  "BookOpen": "book-open",
  "Bookmark": "bookmark",
  "Tag": "tag",
  "Paperclip": "paperclip",
  "PenTool": "pen",
  "Pencil": "pencil",
  "Palette": "palette",
  "Camera": "camera",
  "Video": "video",
  "Film": "film",
  "Clapperboard": "clapperboard",
  "Mic": "microphone",
  "MicOff": "microphone-off",
  "Headphones": "headphones",
  "Music": "music",
  "Volume2": "volume-high",
  "VolumeX": "volume-mute",
  "Sliders": "tune",
  "Image": "image",
  "Newspaper": "newspaper",
  "BarChart": "chart-bar",
  "BarChart2": "chart-bar",
  "PieChart": "chart-pie",
  "Check": "check",
  "X": "close",
  "XCircle": "close-circle",
  "Minus": "minus",
  "HelpCircle": "help-circle",
  "AlertCircle": "alert-circle",
  "AlertTriangle": "alert",
  "Info": "information",
  "Settings": "cog",
  "Wrench": "wrench",
  "Hammer": "hammer",
  "Menu": "menu",
  "MoreHorizontal": "dots-horizontal",
  "MoreVertical": "dots-vertical",
  "Grid": "grid",
  "Layout": "view-dashboard",
  "Eye": "eye",
  "EyeOff": "eye-off",
  "Sun": "sun-white",
  "Moon": "moon-waning-crescent",
  "Sparkles": "star-face",
  "Star": "star",
  "Heart": "heart",
  "Smile": "emoticon-happy",
  "Frown": "emoticon-sad",
  "ThumbsUp": "thumb-up",
  "ThumbsDown": "thumb-down",
  "User": "account",
  "Users": "account-group",
  "LogIn": "login",
  "ArrowLeft": "arrow-left",
  "ArrowRight": "arrow-right",
  "ArrowUp": "arrow-up",
  "ArrowDown": "arrow-down",
  "ChevronLeft": "chevron-left",
  "ChevronRight": "chevron-right",
  "ChevronUp": "chevron-up",
  "ChevronDown": "chevron-down",
  "RefreshCw": "refresh",
  "RotateCw": "rotate-right",
  "RotateCcw": "rotate-left",
  "ExternalLink": "open-in-new",
  "Unlink": "link-off",
  "Share2": "share-variant",
  "Send": "send",
  "Mail": "email",
  "Inbox": "inbox",
  "Bell": "bell",
  "BellOff": "bell-off",
  "Home": "home",
  "Building": "office-building",
  "Building2": "factory",
  "Construction": "crane",
  "Bed": "bed",
  "Bath": "bathtub",
  "ShowerHead": "shower",
  "Droplet": "water",
  "Waves": "waves",
  "Snowflake": "snowflake",
  "Wind": "weather-windy",
  "Compass": "compass",
  "Map": "map",
  "Navigation": "navigation",
  "Anchor": "anchor",
  "Car": "car",
  "Truck": "truck",
  "Bus": "bus",
  "Bike": "bicycle",
  "Plane": "airplane",
  "Ship": "ship",
  "Briefcase": "briefcase",
  "ShoppingBag": "shopping",
  "ShoppingCart": "cart",
  "CreditCard": "credit-card",
  "DollarSign": "currency-usd",
  "Euro": "currency-eur",
  "Gift": "gift",
  "Trophy": "trophy",
  "Award": "medal",
  "Medal": "medal",
  "Crown": "crown",
  "Target": "target",
  "Clock": "clock",
  "Calendar": "calendar",
  "Timer": "timer",
  "Hourglass": "hourglass",
  "Scale": "scale",
  "Scissors": "scissors",
  "Box": "package-variant",
  "Layers": "layers",
  "Coffee": "coffee",
  "Utensils": "silverware",
  "Pizza": "pizza",
  "SunDim": "sun-wireless",
  "CloudSun": "weather-partly-cloudy",
  "CloudRain": "weather-rainy",
  "Trees": "tree",
  "Sprout": "sprout",
  "Apple": "apple",
  "Cat": "cat",
  "Dog": "dog",
  "Rabbit": "rabbit",
  "Squirrel": "squirrel",
  "Bird": "bird",
  "Fish": "fish",
  "Turtle": "turtle",
  "Snail": "snail",
  "Lightbulb": "lightbulb",
  "Glasses": "glasses",
  "Ticket": "ticket",
  "PartyPopper": "party-popper",
  "Trash": "trash-can",
  "Upload": "upload",
  "TerminalSquare": "console-line",
  "FileCheck": "file-check",
  "Globe2": "earth-box",
  "Pin": "pin",
  "HeartOff": "heart-off",
  "LockKeyhole": "lock-smart",
  "FileSearch": "file-search",
  "AArrowDown": "aarrow-down",
  "AArrowDownIcon": "aarrow-down-icon",
  "AArrowUp": "aarrow-up",
  "AArrowUpIcon": "aarrow-up-icon",
  "ALargeSmall": "alarge-small",
  "ALargeSmallIcon": "alarge-small-icon",
  "Accessibility": "accessibility",
  "AccessibilityIcon": "accessibility-icon",
  "ActivityIcon": "activity-icon",
  "ActivitySquare": "activity-square",
  "ActivitySquareIcon": "activity-square-icon",
  "AirVent": "air-vent",
  "AirVentIcon": "air-vent-icon",
  "Airplay": "airplay",
  "AirplayIcon": "airplay-icon",
  "AlarmCheck": "alarm-check",
  "AlarmCheckIcon": "alarm-check-icon",
  "AlarmClock": "alarm-clock",
  "AlarmClockCheck": "alarm-clock-check",
  "AlarmClockCheckIcon": "alarm-clock-check-icon",
  "AlarmClockIcon": "alarm-clock-icon",
  "AlarmClockMinus": "alarm-clock-minus",
  "AlarmClockMinusIcon": "alarm-clock-minus-icon",
  "AlarmClockOff": "alarm-clock-off",
  "AlarmClockOffIcon": "alarm-clock-off-icon",
  "AlarmClockPlus": "alarm-clock-plus",
  "AlarmClockPlusIcon": "alarm-clock-plus-icon",
  "AlarmMinus": "alarm-minus",
  "AlarmMinusIcon": "alarm-minus-icon",
  "AlarmPlus": "alarm-plus",
  "AlarmPlusIcon": "alarm-plus-icon",
  "AlarmSmoke": "alarm-smoke",
  "AlarmSmokeIcon": "alarm-smoke-icon",
  "Album": "album",
  "AlbumIcon": "album-icon",
  "AlertCircleIcon": "alert-circle-icon",
  "AlertOctagon": "alert-octagon",
  "AlertOctagonIcon": "alert-octagon-icon",
  "AlertTriangleIcon": "alert-triangle-icon",
  "AlignCenter": "align-center",
  "AlignCenterHorizontal": "align-center-horizontal",
  "AlignCenterHorizontalIcon": "align-center-horizontal-icon",
  "AlignCenterIcon": "align-center-icon",
  "AlignCenterVertical": "align-center-vertical",
  "AlignCenterVerticalIcon": "align-center-vertical-icon",
  "AlignEndHorizontal": "align-end-horizontal",
  "AlignEndHorizontalIcon": "align-end-horizontal-icon",
  "AlignEndVertical": "align-end-vertical",
  "AlignEndVerticalIcon": "align-end-vertical-icon",
  "AlignHorizontalDistributeCenter": "align-horizontal-distribute-center",
  "AlignHorizontalDistributeCenterIcon": "align-horizontal-distribute-center-icon",
  "AlignHorizontalDistributeEnd": "align-horizontal-distribute-end",
  "AlignHorizontalDistributeEndIcon": "align-horizontal-distribute-end-icon",
  "AlignHorizontalDistributeStart": "align-horizontal-distribute-start",
  "AlignHorizontalDistributeStartIcon": "align-horizontal-distribute-start-icon",
  "AlignHorizontalJustifyCenter": "align-horizontal-justify-center",
  "AlignHorizontalJustifyCenterIcon": "align-horizontal-justify-center-icon",
  "AlignHorizontalJustifyEnd": "align-horizontal-justify-end",
  "AlignHorizontalJustifyEndIcon": "align-horizontal-justify-end-icon",
  "AlignHorizontalJustifyStart": "align-horizontal-justify-start",
  "AlignHorizontalJustifyStartIcon": "align-horizontal-justify-start-icon",
  "AlignHorizontalSpaceAround": "align-horizontal-space-around",
  "AlignHorizontalSpaceAroundIcon": "align-horizontal-space-around-icon",
  "AlignHorizontalSpaceBetween": "align-horizontal-space-between",
  "AlignHorizontalSpaceBetweenIcon": "align-horizontal-space-between-icon",
  "AlignJustify": "align-justify",
  "AlignJustifyIcon": "align-justify-icon",
  "AlignLeft": "align-left",
  "AlignLeftIcon": "align-left-icon",
  "AlignRight": "align-right",
  "AlignRightIcon": "align-right-icon",
  "AlignStartHorizontal": "align-start-horizontal",
  "AlignStartHorizontalIcon": "align-start-horizontal-icon",
  "AlignStartVertical": "align-start-vertical",
  "AlignStartVerticalIcon": "align-start-vertical-icon",
  "AlignVerticalDistributeCenter": "align-vertical-distribute-center",
  "AlignVerticalDistributeCenterIcon": "align-vertical-distribute-center-icon",
  "AlignVerticalDistributeEnd": "align-vertical-distribute-end",
  "AlignVerticalDistributeEndIcon": "align-vertical-distribute-end-icon",
  "AlignVerticalDistributeStart": "align-vertical-distribute-start",
  "AlignVerticalDistributeStartIcon": "align-vertical-distribute-start-icon",
  "AlignVerticalJustifyCenter": "align-vertical-justify-center",
  "AlignVerticalJustifyCenterIcon": "align-vertical-justify-center-icon",
  "AlignVerticalJustifyEnd": "align-vertical-justify-end",
  "AlignVerticalJustifyEndIcon": "align-vertical-justify-end-icon",
  "AlignVerticalJustifyStart": "align-vertical-justify-start",
  "AlignVerticalJustifyStartIcon": "align-vertical-justify-start-icon",
  "AlignVerticalSpaceAround": "align-vertical-space-around",
  "AlignVerticalSpaceAroundIcon": "align-vertical-space-around-icon",
  "AlignVerticalSpaceBetween": "align-vertical-space-between",
  "AlignVerticalSpaceBetweenIcon": "align-vertical-space-between-icon",
  "Ambulance": "ambulance",
  "AmbulanceIcon": "ambulance-icon",
  "Ampersand": "ampersand",
  "AmpersandIcon": "ampersand-icon",
  "Ampersands": "ampersands",
  "AmpersandsIcon": "ampersands-icon",
  "Amphora": "amphora",
  "AmphoraIcon": "amphora-icon",
  "AnchorIcon": "anchor-icon",
  "Angry": "angry",
  "AngryIcon": "angry-icon",
  "Annoyed": "annoyed",
  "AnnoyedIcon": "annoyed-icon",
  "Antenna": "antenna",
  "AntennaIcon": "antenna-icon",
  "Anvil": "anvil",
  "AnvilIcon": "anvil-icon",
  "Aperture": "aperture",
  "ApertureIcon": "aperture-icon",
  "AppWindow": "app-window",
  "AppWindowIcon": "app-window-icon",
  "AppWindowMac": "app-window-mac",
  "AppWindowMacIcon": "app-window-mac-icon",
  "AppleIcon": "apple-icon",
  "ArchiveIcon": "archive-icon",
  "ArchiveRestore": "archive-restore",
  "ArchiveRestoreIcon": "archive-restore-icon",
  "ArchiveX": "archive-x",
  "ArchiveXIcon": "archive-xicon",
  "AreaChart": "area-chart",
  "AreaChartIcon": "area-chart-icon",
  "Armchair": "armchair",
  "ArmchairIcon": "armchair-icon",
  "ArrowBigDown": "arrow-big-down",
  "ArrowBigDownDash": "arrow-big-down-dash",
  "ArrowBigDownDashIcon": "arrow-big-down-dash-icon",
  "ArrowBigDownIcon": "arrow-big-down-icon",
  "ArrowBigLeft": "arrow-big-left",
  "ArrowBigLeftDash": "arrow-big-left-dash",
  "ArrowBigLeftDashIcon": "arrow-big-left-dash-icon",
  "ArrowBigLeftIcon": "arrow-big-left-icon",
  "ArrowBigRight": "arrow-big-right",
  "ArrowBigRightDash": "arrow-big-right-dash",
  "ArrowBigRightDashIcon": "arrow-big-right-dash-icon",
  "ArrowBigRightIcon": "arrow-big-right-icon",
  "ArrowBigUp": "arrow-big-up",
  "ArrowBigUpDash": "arrow-big-up-dash",
  "ArrowBigUpDashIcon": "arrow-big-up-dash-icon",
  "ArrowBigUpIcon": "arrow-big-up-icon",
  "ArrowDown01": "arrow-down01",
  "ArrowDown01Icon": "arrow-down01-icon",
  "ArrowDown10": "arrow-down10",
  "ArrowDown10Icon": "arrow-down10-icon",
  "ArrowDownAZ": "arrow-down-az",
  "ArrowDownAZIcon": "arrow-down-azicon",
  "ArrowDownAz": "arrow-down-az",
  "ArrowDownAzIcon": "arrow-down-az-icon",
  "ArrowDownCircle": "arrow-down-circle",
  "ArrowDownCircleIcon": "arrow-down-circle-icon",
  "ArrowDownFromLine": "arrow-down-from-line",
  "ArrowDownFromLineIcon": "arrow-down-from-line-icon",
  "ArrowDownIcon": "arrow-down-icon",
  "ArrowDownLeft": "arrow-down-left",
  "ArrowDownLeftFromCircle": "arrow-down-left-from-circle",
  "ArrowDownLeftFromCircleIcon": "arrow-down-left-from-circle-icon",
  "ArrowDownLeftFromSquare": "arrow-down-left-from-square",
  "ArrowDownLeftFromSquareIcon": "arrow-down-left-from-square-icon",
  "ArrowDownLeftIcon": "arrow-down-left-icon",
  "ArrowDownLeftSquare": "arrow-down-left-square",
  "ArrowDownLeftSquareIcon": "arrow-down-left-square-icon",
  "ArrowDownNarrowWide": "arrow-down-narrow-wide",
  "ArrowDownNarrowWideIcon": "arrow-down-narrow-wide-icon",
  "ArrowDownRight": "arrow-down-right",
  "ArrowDownRightFromCircle": "arrow-down-right-from-circle",
  "ArrowDownRightFromCircleIcon": "arrow-down-right-from-circle-icon",
  "ArrowDownRightFromSquare": "arrow-down-right-from-square",
  "ArrowDownRightFromSquareIcon": "arrow-down-right-from-square-icon",
  "ArrowDownRightIcon": "arrow-down-right-icon",
  "ArrowDownRightSquare": "arrow-down-right-square",
  "ArrowDownRightSquareIcon": "arrow-down-right-square-icon",
  "ArrowDownSquare": "arrow-down-square",
  "ArrowDownSquareIcon": "arrow-down-square-icon",
  "ArrowDownToDot": "arrow-down-to-dot",
  "ArrowDownToDotIcon": "arrow-down-to-dot-icon",
  "ArrowDownToLine": "arrow-down-to-line",
  "ArrowDownToLineIcon": "arrow-down-to-line-icon",
  "ArrowDownUp": "arrow-down-up",
  "ArrowDownUpIcon": "arrow-down-up-icon",
  "ArrowDownWideNarrow": "arrow-down-wide-narrow",
  "ArrowDownWideNarrowIcon": "arrow-down-wide-narrow-icon",
  "ArrowDownZA": "arrow-down-za",
  "ArrowDownZAIcon": "arrow-down-zaicon",
  "ArrowDownZa": "arrow-down-za",
  "ArrowDownZaIcon": "arrow-down-za-icon",
  "ArrowLeftCircle": "arrow-left-circle",
  "ArrowLeftCircleIcon": "arrow-left-circle-icon",
  "ArrowLeftFromLine": "arrow-left-from-line",
  "ArrowLeftFromLineIcon": "arrow-left-from-line-icon",
  "ArrowLeftIcon": "arrow-left-icon",
  "ArrowLeftRight": "arrow-left-right",
  "ArrowLeftRightIcon": "arrow-left-right-icon",
  "ArrowLeftSquare": "arrow-left-square",
  "ArrowLeftSquareIcon": "arrow-left-square-icon",
  "ArrowLeftToLine": "arrow-left-to-line",
  "ArrowLeftToLineIcon": "arrow-left-to-line-icon",
  "ArrowRightCircle": "arrow-right-circle",
  "ArrowRightCircleIcon": "arrow-right-circle-icon",
  "ArrowRightFromLine": "arrow-right-from-line",
  "ArrowRightFromLineIcon": "arrow-right-from-line-icon"
};

export function normalizeEmoji(emoji: string): string {
  if (!emoji) return '';
  return emoji.replace(/[\ufe00-\ufe0f]/g, '').trim();
}

export const NORMALIZED_EMOJI_TO_LUCIDE: Record<string, string> = {};
export const LUCIDE_TO_EMOJI: Record<string, string> = {};

Object.entries(EMOJI_TO_LUCIDE).forEach(([k, v]) => {
  const normK = normalizeEmoji(k);
  NORMALIZED_EMOJI_TO_LUCIDE[normK] = v;
  
  const normV = v.toLowerCase().trim();
  if (!LUCIDE_TO_EMOJI[normV]) {
    LUCIDE_TO_EMOJI[normV] = k;
  }
});

export function getEmojiCodePoint(emoji: string): string {
  const codePoints = [];
  for (const char of emoji) {
    const cp = char.codePointAt(0);
    if (cp) {
      if (cp === 0xfe0f) continue;
      codePoints.push(cp.toString(16));
    }
  }
  return codePoints.join('-');
}

function getIconFileName(lucideName: string, library: 'tabler' | 'bootstrap' | 'mdi'): string {
  if (library === 'tabler' && TABLER_MAP[lucideName]) return TABLER_MAP[lucideName];
  if (library === 'bootstrap' && BOOTSTRAP_MAP[lucideName]) return BOOTSTRAP_MAP[lucideName];
  if (library === 'mdi' && MDI_MAP[lucideName]) return MDI_MAP[lucideName];
  
  return lucideName.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

const SVG_CACHE = new Map<string, string>();

function SvgCdnIcon({
  src,
  fallbackLucideName,
  className,
  style
}: {
  src: string;
  fallbackLucideName: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  const [svgContent, setSvgContent] = useState<string | null>(() => SVG_CACHE.get(src) || null);
  const [error, setError] = useState(false);

  useEffect(() => {
    let isMounted = true;

    if (SVG_CACHE.has(src)) {
      setSvgContent(SVG_CACHE.get(src)!);
      setError(false);
      return;
    }

    setError(false);
    setSvgContent(null);

    fetch(src)
      .then(res => {
        if (!res.ok) throw new Error('CDN Icon not found');
        return res.text();
      })
      .then(text => {
        if (!isMounted) return;
        let cleanText = text.replace(/<\?xml[\s\S]*?\?>/i, '').replace(/<!DOCTYPE[\s\S]*?>/i, '').trim();
        cleanText = cleanText.replace(/width="[^"]*"/gi, '').replace(/height="[^"]*"/gi, '');
        cleanText = cleanText.replace(/stroke="[^"]*"/gi, 'stroke="currentColor"');
        cleanText = cleanText.replace(/fill="(?!none)[^"]*"/gi, 'fill="currentColor"');
        
        SVG_CACHE.set(src, cleanText);
        setSvgContent(cleanText);
      })
      .catch(() => {
        if (isMounted) setError(true);
      });

    return () => {
      isMounted = false;
    };
  }, [src]);

  if (error || !svgContent) {
    const IconComponent = (LucideIcons as any)[fallbackLucideName] || LucideIcons.HelpCircle;
    return (
      <IconComponent
        className={className}
        style={{
          display: 'inline-block',
          width: '1.2em',
          height: '1.2em',
          verticalAlign: '-0.15em',
          ...style
        }}
      />
    );
  }

  return (
    <span
      className={className}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '1.2em',
        height: '1.2em',
        verticalAlign: '-0.15em',
        ...style
      }}
      dangerouslySetInnerHTML={{ __html: svgContent }}
    />
  );
}

interface EmojiProps {
  emoji: string;
  className?: string;
  style?: React.CSSProperties;
  forcedTheme?: 'native' | 'twemoji' | 'blobmoji' | 'openmoji' | 'lucide' | 'tabler' | 'bootstrap' | 'mdi';
}

export function Emoji({ emoji, className, style, forcedTheme }: EmojiProps) {
  const { config } = useConfig();
  const theme = (forcedTheme || config?.settings?.emojiTheme || 'native') as EmojiProps['forcedTheme'];
  const [loadError, setLoadError] = useState(false);

  if (!emoji) return null;

  if (emoji.startsWith('lucide:')) {
    const iconName = emoji.replace('lucide:', '');
    
    if (theme !== 'lucide' && theme !== 'tabler' && theme !== 'bootstrap' && theme !== 'mdi') {
      const cleanIconName = iconName.toLowerCase().trim();
      const mappedEmoji = LUCIDE_TO_EMOJI[cleanIconName] || '🧩';
      return <Emoji emoji={mappedEmoji} forcedTheme={theme} className={className} style={style} />;
    }
    
    if (theme === 'lucide') {
      const IconComponent = (LucideIcons as any)[iconName];
      if (IconComponent) {
        return (
          <IconComponent
            className={className}
            style={{
              display: 'inline-block',
              width: '1.2em',
              height: '1.2em',
              verticalAlign: '-0.15em',
              ...style
            }}
          />
        );
      }
    } else {
      const kebabName = getIconFileName(iconName, theme);
      let src = '';
      if (theme === 'tabler') {
        src = `https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/${kebabName}.svg`;
      } else if (theme === 'bootstrap') {
        src = `https://cdn.jsdelivr.net/npm/bootstrap-icons@latest/icons/${kebabName}.svg`;
      } else if (theme === 'mdi') {
        src = `https://cdn.jsdelivr.net/npm/@mdi/svg@latest/svg/${kebabName}.svg`;
      }
      
      return <SvgCdnIcon src={src} fallbackLucideName={iconName} className={className} style={style} />;
    }
  }

  if (theme === 'lucide' || theme === 'tabler' || theme === 'bootstrap' || theme === 'mdi') {
    const cleanEmoji = normalizeEmoji(emoji);
    const mappedIconName = NORMALIZED_EMOJI_TO_LUCIDE[cleanEmoji];
    
    const fallbackIcon = 'HelpCircle';
    const finalIconName = mappedIconName || fallbackIcon;
    
    if (theme === 'lucide') {
      const IconComponent = (LucideIcons as any)[finalIconName];
      if (IconComponent) {
        return (
          <IconComponent
            className={className}
            style={{
              display: 'inline-block',
              width: '1.2em',
              height: '1.2em',
              verticalAlign: '-0.15em',
              ...style
            }}
          />
        );
      }
    } else {
      const kebabName = getIconFileName(finalIconName, theme);
      let src = '';
      if (theme === 'tabler') {
        src = `https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/${kebabName}.svg`;
      } else if (theme === 'bootstrap') {
        src = `https://cdn.jsdelivr.net/npm/bootstrap-icons@latest/icons/${kebabName}.svg`;
      } else if (theme === 'mdi') {
        src = `https://cdn.jsdelivr.net/npm/@mdi/svg@latest/svg/${kebabName}.svg`;
      }
      
      return <SvgCdnIcon src={src} fallbackLucideName={finalIconName} className={className} style={style} />;
    }
  }

  if (theme === 'native' || loadError) {
    return <span className={className} style={style}>{emoji}</span>;
  }

  const cp = getEmojiCodePoint(emoji);
  let src = '';

  if (theme === 'twemoji') {
    src = `https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/svg/${cp}.svg`;
  } else if (theme === 'blobmoji') {
    src = `https://cdn.jsdelivr.net/gh/C1710/blobmoji@master/svg/${cp}.svg`;
  } else if (theme === 'openmoji') {
    src = `https://openmoji.org/data/color/svg/${cp.toUpperCase()}.svg`;
  }

  if (!src) {
    return <span className={className} style={style}>{emoji}</span>;
  }

  return (
    <img
      src={src}
      alt={emoji}
      className={className}
      style={{
        display: 'inline-block',
        width: '1.2em',
        height: '1.2em',
        verticalAlign: '-0.15em',
        objectFit: 'contain',
        ...style
      }}
      onError={() => {
        setLoadError(true);
      }}
    />
  );
}
